# [1] Numpy: ndarray 기초

### [실습] 다양한 방법으로 배열 생성


NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [1]:
import numpy as np

In [3]:
# 1. 크기가 4x3인 모든 값이 0인 배열
arr1 = np.zeros((4,3))
print(arr1)
print("-" * 50)
# 2. 크기가 3x3인 모든 값이 1인 배열
arr2 = np.ones((3,3))
print(arr2)
print("-" * 50)
# 3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
arr3 = np.arange(0,20,5)
print(arr3)
print("-" * 50)
# 4. 0과 1 사이의 4개의 등간격 값을 가진 배열
arr4 = np.linspace(0,1,4)
print(arr4)
print("-" * 50)

# 5. 크기가 2x2인 정규 분포로 구성된 배열
arr5 = np.random.normal(0,1,(2,2))
print(arr5)
print("-" * 50)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
[ 0  5 10 15]
--------------------------------------------------
[0.         0.33333333 0.66666667 1.        ]
--------------------------------------------------
[[ 0.84135072 -0.08213587]
 [-0.01443265  0.02790374]]
--------------------------------------------------
