# [5] Numpy: 정렬

### [실습 1] 1차원 배열 정렬


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.


```python
arr = np.array([50, 10, 30, 40, 20])
```

In [1]:
import numpy as np

In [13]:
arr = np.array([50, 10, 30, 40, 20])
print("arr_asc:", np.sort(arr))
print("arr_desc:", arr[np.argsort(-arr)])

arr_asc: [10 20 30 40 50]
arr_desc: [50 40 30 20 10]


### [실습 2] 2차원 배열 축 기준 정렬


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.


```python
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [16]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

indices = np.argsort(arr2d, axis = 0)
print(indices)
print(arr[indices])

indices2 = np.argsort(arr2d, axis = 1)
print(indices2)
print(arr[indices2])

[[1 0 1]
 [0 1 0]]
[[10 50 10]
 [50 10 50]]
[[1 2 0]
 [2 0 1]]
[[10 30 50]
 [30 50 10]]


### [실습 3] 인덱스를 반환하는 정렬


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.


```python
arr = np.array([15, 10, 20])
```

In [17]:
arr = np.array([15, 10, 20])

# 정렬된 결과의 인덱스를 반환
sorted_indices = np.argsort(arr)
print("정렬된 인덱스: ", sorted_indices)

# 그 인덱스를 사용하여 배열을 정렬
sorted_arr = arr[sorted_indices]
print("정렬된 배열: ", sorted_arr)

정렬된 인덱스:  [1 0 2]
정렬된 배열:  [10 15 20]
